# Introducción Algebra Lineal

En este notebook veremos una pequeña introducción álgebra lineal, aprenderemos algunos conceptos básicos:
- Vectores y Matrices 
- Representar ecuaciones con matrices
- Producto escalar
- Matriz identidad
- Matriz inversa


### Representar datos como una matriz

\begin{equation}A=
\begin{bmatrix}
6 & 8 & 1\\
2 & 9 & 3\\
4 & 5 & 1
\end{bmatrix}
\end{equation}

Decimos que `A` es una matriz de `3x3` con `m=3 filas` por `n=3 columnas`. Podemos representar dicha matriz en python usando la librería numpy. Veamos un ejemplo:

In [5]:
import numpy as np

a = np.array([
    [6,8,1],
    [2,9,3],
    [4,5,1]
])

print(a)

[[6 8 1]
 [2 9 3]
 [4 5 1]]


La librería numpy es muy util cuando trabajamos con matrices. Numpy contiene estructuras de datos que permiten trabajar adecuadamente con ellas. Además también nos habilita el poder realizar operaciones directamente con dichas estructuras. Por ejemplo, vamos a multiplicar todos los elementos de la matriz `A` por `10`.

La multiplicación de una matriz por un escalar es una operación elemento a elemento, donde cada elemento de la matriz `A` se multiplica por el escalar α

In [32]:
# Mutliplicar la matriz A por un escalar
a*10

array([[10, 20],
       [30, 40],
       [50, 60]])

## Suma de matrices

Realizar una suma de matrices usando numpy tan sencillo como declarar cada una de las matrices en una variable y usar el operador suma. Es importante que dichas matrices sean declaradas usando `np.array` ya que al no ser así, el operador por defecto `+` no soporta la suma de dos listas `python`

In [28]:
A = np.array([[0,2],
              [1,4]])
B = np.array([[3,1],
              [-3,2]])

A+B

array([[ 3,  3],
       [-2,  6]])

In [30]:
# también podemos realizar la operación usando el método `add`

np.add(A, B)

array([[ 3,  3],
       [-2,  6]])

## Ecuaciones en formato matriz

\begin{equation}
Ax = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
\end{bmatrix}
\end{equation}

La siguiente ecuación se expresa como combinación de las columnas. Podemos expresar la ecuación también de la siguiente forma:

\begin{equation}
Ax = x_1\begin{bmatrix}
1 \\
3 \\
5
\end{bmatrix}
+
x_2\begin{bmatrix}
2 \\
4 \\
6
\end{bmatrix}
\end{equation}


### Producto escalar

Es una operación algebraica que toma dos secuencias de números de igual longitud (usualmente en la forma de vectores) y retorna un único número

https://es.wikipedia.org/wiki/Producto_escalar

Los 3 componentes de la ecuación `Ax` son los productos escalares de las 3 filas de `A`con el vector `x`. Imaginemos que el vector `x` tomase los valores $x_1=7$, $x_2=8$

En ese caso el resultado de A sería:

$$
\begin{equation}
\begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
\begin{bmatrix}
7\\
8\\
\end{bmatrix}
=
\begin{bmatrix}
1·7 + 2·8\\
3·7 + 4·8\\
5·7 + 6·8
\end{bmatrix}
=
\begin{bmatrix}
23\\
53\\
83
\end{bmatrix}
\end{equation}
$$

Calculando dichos valores con python y numpy nos quedará:


In [24]:
a = np.array([[1,2],[3,4],[5,6]])
x = np.array([[7],[8]])

print("Matriz: \n",a)
print("Vector X: \n",x)

## La operación np.dot representa el producto escalar
np.dot(a,x)

Matriz: 
 [[1 2]
 [3 4]
 [5 6]]
Vector X: 
 [[7]
 [8]]


array([[23],
       [53],
       [83]])

Es importante remacar que la representación en python del vector `x` debe ser en formato columna, **por eso introducimos dobles corchetes** indicando una lista dentro de otra lista `[[7],[8]]`. 

Para que la multiplicación de dos matrices pueda realizarse, el número columnas en la primera matriz `A` tiene que ser igual al número de filas en la segunda matriz `X`. Otra forma de ver la multiplicación entre matrices es verlo como una serie de productos escalares: la primera columna de `A` multiplicada por la primera fila de `B`, la segunda columna de `A` multiplicada por la segunda fila de `B`, y sucesivas.

Para poder ver las filas y columnas de una matriz podemos ver la propiedad `shape`


In [34]:
a.shape

(3, 2)

Como vemos, la matriz `A` contiene `(3 filas, 2 columnas)`


### Listas
Las listas son una estructura básica de código, y representan una sucesión ordenada de datos. Encontrarás mas ejemmplos en este enlace:
- https://www.programiz.com/python-programming/list

## Matriz identidad

Una matriz identidad es una matriz cuadrada (mismas filas que columnas), cuyos valor es siempre cero excepto en la diagonal de izquierda a derecha, en la que el valor es `1`.

Reporesentamos la matriz identidad como $\mathbb{1}∈ℝn×n$

Podemos imaginar la matriz identidad como una matriz con el mismo rol que el valor `1` en las operaciones con numeros reales, donde cualquier valor mutliplicado por `1` es exactamente el mismo valor. Esta matriz sin embargo juega un rol muy importante en demostraciones matematicas y en la matriz inversa (que sirve para resolver sistemas de ecuaciones lineales)

Podemos crear una matriz identidad en `numpy` usando el siguiente método:


In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Inversa de una matriz

En el contexto de los numeros reales [https://en.wikipedia.org/wiki/Real_number] la inversa mutliplicativa de un número `x` es un numero que al multiplicar por `x` el resultado sea `1`. Nos referiremos a ese número como $x^-1$ o $\frac{1}{x}$. Por ejemplo, toma el número 5. Su inversa será igual a $5·\frac{1}{5} = 1$


En la sección sobre la matriz identidad, mencionamos que dicha matriz juega un papel similar al número 1, pero para las matrices. De nuevo, como analogía, podemos decir que la inversa de una matriz representa el mismo rol que la inversa mutliplicativa pero para las matrices. Por tanto, la inversa de una matriz es una matriz tal que al ser multiplicada por la primera tanto a la izquierda como a la derecha, devuelve la matriz identidad (representada por el símbolo $\mathbb{1}$).


Mas formalmente, considera la matriz cuadrada $A∈ℝn×n$. Definimos la inversa $A^-1$ con la siguiente propiedad:


$$A^-1·A=A·A^−1=\mathbb{1}$$

La razón de interés principal referente a la inversa, es que nos permite resolver sistemas de ecuaciones lineales en ciertas circunstancias. Considera el siguiente sistema de ecuaciones lineales:

$Ax=y$ 

Suponiendo que `A` tiene inversa, podemos multiplicar por la inversa en ambos lados del igual 


$A^−1·A·x=A^-1·y$

y obtener:

$\mathbb{1}·x=A^−1·y$

Como la matriz identidad $\mathbb{1}$ no afecta a `x`, la expresión final para resolver la ecuación y encontrar el valor de la matriz `x` es la siguiente:

$x=A^-1·y$ 

Esta expresión nos aclara que para resovler dicho sistema de ecuaciones lineales solo necesitamos saber el valor de la inversa de A y mutliplicarla por el valor del vector `y`, entonces obtendremos la solución para nuestro sietema. 

Tal y como hemos indicado, esto solo funciona en algunas situaciones. Nos referimos a que esto solo sucede en caso que la matriz inicial `A` sea invertible, y la realidad es que **no todas las matrices tienen inversa**. Cuando exista $A^-1$ decimos que es invertible o `no-singular`, en caso contrario decimos que no es invertible o `singular`.

En numpy podemos calcular la inversa de una matriz de la siguiente forma:


In [46]:
A = np.array([[1, 2, 1],
              [4, 4, 5],
              [6, 7, 7]])

A_i = np.linalg.inv(A)
print(f'A inversa:\n{A_i}')

A inversa:
[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


Podemos comprobar que la matriz inversa es correcta realizando la multiplicación de ambas y esperando la matriz identidad $\mathbb{1}$ como resultado:

In [47]:
# Comprobamos que el resultado de multiplicar A por su A_i (su inversa) es la identidad
np.round(A_i @ A)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])