<img src="https://api.brandy.run/core/logo" width="80"/>

# CORE Code School

## Numpy y las matrices inversas
### Computación Analítica vs Numérica

$$
\begin{equation}A=
\begin{bmatrix}
21 & 32 & 43 & 54\\
22 & 33 & 44 & 56\\
23 & 34 & 45 & 57\\
24 & 35 & 46 & 58\\
\end{bmatrix}
\end{equation}
$$

😎

In [1]:
import numpy as np
A = np.array([[21, 32, 43, 54],
              [22, 33, 44, 56],
              [23, 34, 45, 57],
              [24, 35, 46, 58]])

In [2]:
print(A)

[[21 32 43 54]
 [22 33 44 56]
 [23 34 45 57]
 [24 35 46 58]]


Sacamos la matriz inversa

In [3]:
x = 33
x_inv = 1/x

$$
x * x' = 1
$$

In [4]:
x * x_inv

1.0

In [5]:
x = 7/4
x_inv = 4/7

In [6]:
x * x_inv

1.0

- Tenemos matriz A
- Queremos la inversa de A: A'

de forma que

$$
A \cdot A' = I
$$

In [7]:
A

array([[21, 32, 43, 54],
       [22, 33, 44, 56],
       [23, 34, 45, 57],
       [24, 35, 46, 58]])

In [8]:
A.shape

(4, 4)

In [9]:
np.identity(A.shape[0])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 2.42109091e+00  3.95920846e+14 -7.91841693e+14  3.95920846e+14]
 [-5.93309091e+00 -7.91841693e+14  1.58368339e+15 -7.91841693e+14]
 [ 4.51200000e+00  3.95920846e+14 -7.91841693e+14  3.95920846e+14]
 [-1.00000000e+00  2.06043956e+00 -1.12087912e+00  6.04395604e-02]]


In [11]:
print(np.dot(A,A_inv))

[[ 1.00000000e+00 -6.11263736e-01 -1.52747253e+00 -6.73763736e-01]
 [-2.22044605e-14  1.88461538e+00  1.23076923e+00 -3.65384615e-01]
 [-1.85407245e-14  3.20054945e-01  1.10989011e+00 -1.17445055e-01]
 [-1.48769885e-14  7.55494505e-01 -3.01098901e+00  1.30494505e-01]]


# Resultado != Matriz Identidad
¿Por qué? Porque A no es inversible. 😕 

Pero si... Numpy.... linalg.inv... 🥸

# Investiguemos...
Bueno, las matrices singulares (que no poseen iversas) tienen determinante cero.

Entonces lo primero es calcular el determinante.

## Que es el determinante?

In [12]:
B = np.array([[1,4],
              [5,6]])
print(B)

[[1 4]
 [5 6]]


In [13]:
1*6 - 4*5

-14

In [14]:
np.linalg.det(B)

-13.999999999999996

In [15]:
round(np.linalg.det(B))

-14

## La matriz A tiene determinante != 0?

In [16]:
np.linalg.det(A)

-2.7783331191244748e-14

$$
x^2 -2x = 18
$$

$$
x^2 -2x -18 = 0
$$

$$
\Delta = b^2 - 4ac
$$
$$
x = \frac{-b +- \sqrt{\Delta}}{2a}
$$

In [17]:
a,b,c = 1,-2,-18
delta = b**2 - 4*a*c

In [18]:
delta

76

In [19]:
x_pos = (-b + delta**.5)/(2*a)
x_neg = (-b - delta**.5)/(2*a)

In [20]:
x_pos,x_neg

(5.358898943540674, -3.358898943540674)

$$
x^2 -2x -18 = 0
$$

In [21]:
x = 0
res = x**2-2*x-18
res

-18

In [22]:
x = 1
res = x**2-2*x-18
res

-19

In [23]:
x = 5
res = x**2-2*x-18
res

-3

In [24]:
x = 5.358
res = x**2-2*x-18
res

-0.007836000000004617

In [25]:
from math import isclose

In [26]:
isclose(-.5,0,abs_tol=.5)

True

In [27]:
%%time
limit = 0.5
step = 0.1

x = 0

i=0
while True:
    i+=1
    res = x**2-2*x-18
    if isclose(res,0,abs_tol=limit):
        print(x)
        break
    x = x-step

-3.4000000000000017
CPU times: user 72 µs, sys: 52 µs, total: 124 µs
Wall time: 56 µs


In [28]:
i

35

In [29]:
x = -3.4
res = x**2-2*x-18
res

0.35999999999999943

# No es cero... O será? 🤔

Vamos calcular manualmente. [Sobre el metodo para calcular el determinante de matrices de tamaño 4x4 y mayores](https://www.mathsisfun.com/algebra/matrix-determinant.html)

In [30]:
def det(mat):
    res = 0
    sig = 1
    if mat.shape == (2,2):
        return mat[0,0]*mat[1,1] - mat[0,1]*mat[1,0]
    else:
        for i in range(mat.shape[1]):
            res += mat[0,i]*det(np.delete(mat[1:,:], i,1)) * sig
            sig = - sig
    return res

In [31]:
det(A)

0

In [32]:
np.linalg.det(A)

-2.7783331191244748e-14

In [33]:
-2.778 * 10**-14

-2.778e-14

In [34]:
0.00000000000002778

2.778e-14

<img src="img/fine.jpeg"/>

Ahora que nos vamos a profundizar en el mundo de la computación, empezamos presentando dos de los paradigmas y "problemas" (más bien consideraciones) de ese universo.

Los ordenadores no piensan, sino que computan. Eso es, hacen calculos matemáticos, aritméticos y más especificamente en binario. 0️⃣1️⃣0️⃣0️⃣1️⃣1️⃣1️⃣0️⃣1️⃣0️⃣1️⃣

Por un lado, enfrentamos la diferencia entre el método Analítico y el método Numérico.

### Método Analítico

El método analítico es como aprendemos a solucionar problemas matemáticos tradicionalmente. Seguimos una serie de reglas lógicas para aíslar determinado parámetro y al final le computamos con valores.

### Método Numérico

En el método numérico, delante de un problema, imputamos valores repetidamente hasta que lleguemos lo cerca bastante de la solución. Esa solución puede o no ser igual a la del anterior método, dependiendo de la complejidad  del problema y de la precisión de el sistema. 

### Los ordenadores

Aunque sea posíble hacer soluciones analíticas (también llamadas simbólicas) usando diferentes librerias, siempre será una situación de encontrar un compromiso entre la precisión de el resultado y el coste computacional.

Los métodos numéticos insertan pequeños errores, pero que son perfectamente aceptables. En general las librerias de computación simbólica son usadas en casos muy específicos. Y nos beneficiamos mucho más al hacer un mayor número de cálculos numéricos, que utilizan operaciones más simples.

In [35]:
from IPython.display import IFrame
IFrame('https://www.youtube.com/embed/F2NWYEOHIkc"', width=560, height=315)

La segunda mitad de esa cuestión se da en el fato de que los ordenadores utilizan aritmética binária. Y para la representación de los numeros en los bits de un procesador, se utiliza una manera de interpretar esos numeros que se llama:

### Floating Point Numbers

Si pensamos en la representación de numeros en binário, obtenemos lo siguiente:

|decimal|binário||decimal|binário|
|---|--|--|--|--|
|0|0000||8|1000|
|1|0001||9|1001|
|2|0010||10|1010|
|3|0011||11|1011|
|4|0100||12|1100|
|5|0101||13|1101|
|6|0110||14|1110|
|7|0111||15|1111|

Si quisieramos representar el numero decimal 16, necesitariamos un bit más (cada bit es un valor 0 o 1), puesto que en la tabla solo tenemos 4, que permiten representar desde el 0 hasta el 15. En los ordenadores comunmente encontrados en el día de hoy, tenemos procesadores capaces de computar valores de 32 o 64 bit.

O sea, el máximo numero que podríamos representar como un entero en 64 bits es el valor:

In [36]:
num = 0
for i in range(64):
    num += 2**i
num

18446744073709551615

Ese limite es irrelevante en Python, todavía, pués los enteros en Python no son enternos nativos de el lenguaje de máquina, sino que Python es una capa extra que permite que numeros más grandes.

In [37]:
num + 1

18446744073709551616

Pero fijaos que pasa si intentamos convertir ese numero en un int64 de numpy.

In [38]:
np.int64(num)

OverflowError: Python int too large to convert to C long

Obtenemos un error muy específicio que es un error de `Overflow`, i.e.: que intentamos utilizar más bits que los disponibles. Eso porque, como especificado en el mensaje del error, numpy está escrito en un otro lenguaje de programación, `C`, que tiene diferentes limitaciones.

De cualquier manera, el limite teorico calculado anteriormente considerara apenas los enteros positivos. Si usaramos un `bit` para marcar el signo de positivo o negativo, llegamos al limite real.

In [39]:
num = 0
for i in range(63):
    num += 2**i
num

9223372036854775807

Y ese numero podemos convertir sin problemas a un entero de numpy.

In [40]:
num = np.int64(num)
num

9223372036854775807

Pero si intentamos sumarle uno...

In [41]:
num + 1

/var/folders/xc/2hbgx_ys6pn64tvbcj1r62qw0000gn/T/ipykernel_62788/1907636913.py:1: RuntimeWarning: overflow encountered in long_scalars
  num + 1


-9223372036854775808

En el overflow, el bit significativo esta fuera de la cantidad de bits disponibles y por lo tanto no se le. Así que damos la vuelta desde el mayor numero al menor, por lo que tenemos un numero negativo.

Hemos visto que para utilizar un unico bit para el signo de positivo o negativo ya reduce en una potencia de 2 el numero maximo que podemos representar. Si fueramos guardar más información en ese numero, también perderiamos precisión, como es el caso de los numeros reales, que se computan como `floating points`.

Los numeros de `coma flotante` son numeros representados en el formato de notación científica, como:

$$
0.0625  = 6.25 * 10^{-2}
$$

La parte significativa del numero en esa representación (6.25) se llama `mantissa` y la otra el `exponent`.

En binario representariamos ese numero de la siguiente manera, con el punto decimal (coma) después de el primer digito significativo:

![Floating Point](img/float.png)

Lo convertimos a base 10.

### Mantissa

|neg.|512|256|128|64|32|16|8|4|2|1|
|-|-|-|-|-|-|-|-|-|-|-|
|0|1|0|0|1|1|1|0|0|0|1|

$$
512 + 64 + 32 + 16 + 1 = 625
$$

O con el punto, `6.25`.

### Exponent

|neg.|8|4|2|1|
|-|-|-|-|-|
|1|0|0|1|0|

$$
-2
$$

Y volvemos obtener :

$$
6.25 * 10^{-2}
$$

### 64bit

Segun el [standard](https://en.wikipedia.org/wiki/IEEE_754) la maior parte de los ordenadores de 64 bits usaran 53 para la mantissa y 11 para el exponent.

## Floating Point Error

Imaginemos lo siguiente ahora. Queremos representar el numero $1/3$, que en decimal se representa como $0.3333333...$, la repetición infinita $0.\overline{3}$.

Ese numero se representaria de la misma manera que el ejemplo arriba en binario.

![Floating Point](img/floaterror.png)

O sea:

|neg.|512|256|128|64|32|16|8|4|2|1|
|-|-|-|-|-|-|-|-|-|-|-|
|0|0|1|0|1|0|0|1|1|0|1|

$$
256 + 64 + 8 + 4 + 1 = 333
$$

Por lo tanto, la maxima precisión en 16 bits seria $0.333$, pues los ordenadores son incapaces de comprender la repetición infinita por defecto.

Cuanto más bits tengamos disponible, más precisión podríamos tener en ese numero.

Si sumaramos 0.333 + 0.333 + 0.333 en binario, con 16 digitos obtendríamos el resultado `0.999`, de manera que:

$$
1/3 + 1/3 + 1/3 \ne 1
$$

Ese error se llama `error de coma flotante`, pues los numeros que no se pueden representar en su totalidad (los que possen más digitos significativos de los que están disponibles) se representan como una aproximación.

Aunque en python si hacemos `1/3 + 1/3 + 1/3` obtenemos el resultado `1.0`, pues no sumamos numeros puramente binários, sino que tenemos la "capa extra" que ya hemos citado.

In [ ]:
1/3 + 1/3 + 1/3

In [ ]:
IFrame('https://www.youtube.com/embed/PZRI1IfStY0', width=560, height=315)

Por encima de todo eso, como numpy está optimizado para calcular lo más rápido posible, incluso las inversas de matrices enormes, no utiliza el método analítico como definido en la función para calcular el determinante `det` arriba.

En la computación siempre hay un balance entre precisión y economia de recursos.

In [42]:
mat = np.random.randint(0,10,100).reshape((10,10))
mat

array([[5, 1, 4, 2, 7, 1, 6, 9, 5, 9],
       [7, 2, 1, 3, 7, 6, 2, 1, 9, 6],
       [0, 6, 5, 7, 0, 3, 5, 0, 3, 2],
       [5, 7, 3, 9, 0, 2, 9, 6, 3, 0],
       [2, 2, 6, 8, 4, 6, 7, 9, 1, 7],
       [2, 7, 2, 8, 7, 2, 1, 6, 8, 4],
       [4, 3, 3, 7, 7, 2, 9, 8, 3, 3],
       [7, 8, 6, 8, 5, 4, 4, 8, 1, 1],
       [1, 9, 3, 4, 9, 6, 2, 5, 6, 7],
       [2, 1, 0, 0, 2, 5, 3, 1, 8, 6]])

In [43]:
%%time
res_np = np.linalg.det(mat)

CPU times: user 82 µs, sys: 33 µs, total: 115 µs
Wall time: 113 µs


In [44]:
res_np

224695002.99999997

In [45]:
%%time
res_sym = det(mat)

CPU times: user 7.12 s, sys: 19.4 ms, total: 7.14 s
Wall time: 7.14 s


In [46]:
res_sym

224695003

In [47]:
error = (res_np / res_sym) - 1
print(f"El error del metodo numerico {error*100:.50f} %")

El error del metodo numerico -0.00000000000001110223024625156540423631668090820312 %


In [48]:
delta_t = (7.14 / 115e-6) - 1
print(f"El metodo analítico tarda {delta_t*100} % más")

El metodo analítico tarda 6208595.652173913 % más
